# FULL DOCUMENTATION CAN BE FOUND HERE: #https://docs.gitlab.com/ce/ci/yaml/

# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: golang:1.14-stretch

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
# cache:
#   key: { files: [yarn.lock] }
#   paths: [.ci_cache/, node_modules/]

# run in order.
stages: [test, build, publish]

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
#services:
# you can specify a alias to access the locally attached service.

# https://docs.gitlab.com/ee/ci/yaml/#extends

# runs before each job
before_script:
  # - apk add git curl jq
  - sh -c "$(curl -fsSL https://raw.github.com/techdecaf/tasks/master/install.sh)"

test:
  stage: test
  script: [tasks run dependencies coverage]
  coverage: /total:.*\s([\d\.]+)%/
  only: [branches, tags]
  except: [master]

build:
  stage: build
  script: [tasks run build]
  only: [/^v\d+.\d+.\d+/]
  except: [branches]

pre-release:
  stage: publish
  script: ["echo pre-release"]
  only: [/^v\d+.\d+.\d+/]
  except: [branches]

release:
  stage: publish
  script: ["echo release"]
  only: [/^v\d+.\d+.\d+$/]
  except: [branches]
