# FULL DOCUMENTATION CAN BE FOUND HERE: #https://docs.gitlab.com/ce/ci/yaml/

# image: golang:1.13-alpine

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

stages: [test]

test:
  image: golang:1.13-alpine
  stage: test
  script:
    # - apk add git
    - go test .
