
# documentation for tasks can be found @ https://github.com/techdecaf/tasks
options:
  log: true

variables:
  CI_PROJECT_NAME: unset
  CI_COMMIT_TAG: "{{EXEC `git describe --tags --always --dirty --abbrev=0`}}"
  CI_COMMIT_REF_NAME: "{{EXEC `git rev-parse --abbrev-ref HEAD`}}"
  CI_COMMIT_SHA: "{{EXEC `git rev-parse HEAD`}}"

tasks:
  default:
    description: is the task that runs when no tasks have been specified.
    commands: [tasks list]

  dependencies:
    description: install all required dependencies
    commands: []

  build:
    description: build current project
    pre: [clean, dependencies]
    commands: []

  clean:
    description: remove files created as part of the build step.
    commands: []

  test:
    description: run tests
    commands: []

  lint:
    description: run linting
    commands: []

  deploy:
    description: deploy the current project
    commands: []
